- name: Deploy loadbalancer
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    service_account_email: <your_account_email>
    credentials_file: <your_cred_file>
    project_id: <your_project_id>

  tasks:
    - name: Delete loadbalancer for apa-web-X
      gce_lb:
        name: lbserver
        state: deleted
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
