# Playbook to register a server in RHEL Satellite 6.X
- name: SetUp server in RHEL Sat 6.X
  hosts: servers
  tasks:
    - name: Include the vars file
      include_vars: ../playbk_vardata/satellite_access.yml
    
    - name: Install the Katello RPM from satellite
      shell: "rpm -Uvh http://<your sat server here>/pub/katello-ca-consumer-latest.noarch.rpm"

    - name: Register machine
      redhat_subscription:
        state: present
        username: admin
        password: "{{ sat_password }}"
        pool: "Employee SKU"

    - name: Disable all repos
      shell: "subscription-manager repos --disable=*"

    - name: Enable Satellite server rpms
      shell: "subscription-manager repos --enable rhel-7-server-rpms --enable rhel-7-server-satellite-tools-6.4-rpms"

    - name: Install required packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - katello-agent
        - katello-host-tools-tracer

    - name: Start/Enable services
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
      with_items:
        - goferd
        - rhsmcertd

    - name: Katello package upload
      shell: "katello-tracer-upload"

    - name: Upgrade all packages
      yum:
        name: "*"
        state: latest
      register: systemupgrade

    - set_fact:
        real_ansible_host: "{{ ansible_host }}"

    - name: Reboot machine
      shell: sleep 3 && shutdown -r +1 "Ansible Automation - Reboot will be triggered in 1 minutes"
      async: 1
      poll: 0
      ignore_errors: true

    - name: Wait host to go down
      local_action:
        wait_for host={{ real_ansible_host }}
        port=22 state=absent delay=1 timeout=120
      become: false

    - name: Wait host to start
      local_action:
        wait_for host={{ real_ansible_host }}
        port=22 state=started delay=30 timeout=120
      become: false

    - name: Debug print host
      debug:
        msg "Just finished - {{ ansible_host }}"
